[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['cd backend && python -m pip install -r requirements.txt']

[phases.build]
cmds = ['cd backend && mkdir -p uploads/avatars']

[start]
cmd = 'cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT'